/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AditivosAtualRouteImport } from './routes/aditivos-atual'
import { Route as AeroRouteImport } from './routes/aero'
import { Route as AtasRouteImport } from './routes/atas'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MunicipiosRouteImport } from './routes/municipios'
import { Route as ReceitaRouteImport } from './routes/receita'
import { Route as SigRouteImport } from './routes/sig'
import { Route as VigenciasRouteImport } from './routes/vigencias'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AditivosAtualRoute = AditivosAtualRouteImport.update({
  id: '/aditivos-atual',
  path: '/aditivos-atual',
  getParentRoute: () => rootRouteImport,
} as any)
const AeroRoute = AeroRouteImport.update({
  id: '/aero',
  path: '/aero',
  getParentRoute: () => rootRouteImport,
} as any)
const AtasRoute = AtasRouteImport.update({
  id: '/atas',
  path: '/atas',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipiosRoute = MunicipiosRouteImport.update({
  id: '/municipios',
  path: '/municipios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaRoute = ReceitaRouteImport.update({
  id: '/receita',
  path: '/receita',
  getParentRoute: () => rootRouteImport,
} as any)
const SigRoute = SigRouteImport.update({
  id: '/sig',
  path: '/sig',
  getParentRoute: () => rootRouteImport,
} as any)
const VigenciasRoute = VigenciasRouteImport.update({
  id: '/vigencias',
  path: '/vigencias',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aditivos-atual': typeof AditivosAtualRoute
  '/aero': typeof AeroRoute
  '/atas': typeof AtasRoute
  '/mcp': typeof McpRoute
  '/municipios': typeof MunicipiosRoute
  '/receita': typeof ReceitaRoute
  '/sig': typeof SigRoute
  '/vigencias': typeof VigenciasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aditivos-atual': typeof AditivosAtualRoute
  '/aero': typeof AeroRoute
  '/atas': typeof AtasRoute
  '/mcp': typeof McpRoute
  '/municipios': typeof MunicipiosRoute
  '/receita': typeof ReceitaRoute
  '/sig': typeof SigRoute
  '/vigencias': typeof VigenciasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aditivos-atual': typeof AditivosAtualRoute
  '/aero': typeof AeroRoute
  '/atas': typeof AtasRoute
  '/mcp': typeof McpRoute
  '/municipios': typeof MunicipiosRoute
  '/receita': typeof ReceitaRoute
  '/sig': typeof SigRoute
  '/vigencias': typeof VigenciasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aditivos-atual'
    | '/aero'
    | '/atas'
    | '/mcp'
    | '/municipios'
    | '/receita'
    | '/sig'
    | '/vigencias'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aditivos-atual'
    | '/aero'
    | '/atas'
    | '/mcp'
    | '/municipios'
    | '/receita'
    | '/sig'
    | '/vigencias'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/aditivos-atual'
    | '/aero'
    | '/atas'
    | '/mcp'
    | '/municipios'
    | '/receita'
    | '/sig'
    | '/vigencias'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AditivosAtualRoute: typeof AditivosAtualRoute
  AeroRoute: typeof AeroRoute
  AtasRoute: typeof AtasRoute
  McpRoute: typeof McpRoute
  MunicipiosRoute: typeof MunicipiosRoute
  ReceitaRoute: typeof ReceitaRoute
  SigRoute: typeof SigRoute
  VigenciasRoute: typeof VigenciasRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aditivos-atual': {
      id: '/aditivos-atual'
      path: '/aditivos-atual'
      fullPath: '/aditivos-atual'
      preLoaderRoute: typeof AditivosAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aero': {
      id: '/aero'
      path: '/aero'
      fullPath: '/aero'
      preLoaderRoute: typeof AeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atas': {
      id: '/atas'
      path: '/atas'
      fullPath: '/atas'
      preLoaderRoute: typeof AtasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipios': {
      id: '/municipios'
      path: '/municipios'
      fullPath: '/municipios'
      preLoaderRoute: typeof MunicipiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita': {
      id: '/receita'
      path: '/receita'
      fullPath: '/receita'
      preLoaderRoute: typeof ReceitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sig': {
      id: '/sig'
      path: '/sig'
      fullPath: '/sig'
      preLoaderRoute: typeof SigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vigencias': {
      id: '/vigencias'
      path: '/vigencias'
      fullPath: '/vigencias'
      preLoaderRoute: typeof VigenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AditivosAtualRoute: AditivosAtualRoute,
  AeroRoute: AeroRoute,
  AtasRoute: AtasRoute,
  McpRoute: McpRoute,
  MunicipiosRoute: MunicipiosRoute,
  ReceitaRoute: ReceitaRoute,
  SigRoute: SigRoute,
  VigenciasRoute: VigenciasRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
