/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VigenciasRouteImport } from './routes/vigencias'
import { Route as SigRouteImport } from './routes/sig'
import { Route as ReceitaRouteImport } from './routes/receita'
import { Route as MunicipiosRouteImport } from './routes/municipios'
import { Route as AtasRouteImport } from './routes/atas'
import { Route as AeroRouteImport } from './routes/aero'
import { Route as IndexRouteImport } from './routes/index'

const VigenciasRoute = VigenciasRouteImport.update({
  id: '/vigencias',
  path: '/vigencias',
  getParentRoute: () => rootRouteImport,
} as any)
const SigRoute = SigRouteImport.update({
  id: '/sig',
  path: '/sig',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaRoute = ReceitaRouteImport.update({
  id: '/receita',
  path: '/receita',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipiosRoute = MunicipiosRouteImport.update({
  id: '/municipios',
  path: '/municipios',
  getParentRoute: () => rootRouteImport,
} as any)
const AtasRoute = AtasRouteImport.update({
  id: '/atas',
  path: '/atas',
  getParentRoute: () => rootRouteImport,
} as any)
const AeroRoute = AeroRouteImport.update({
  id: '/aero',
  path: '/aero',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aero': typeof AeroRoute
  '/atas': typeof AtasRoute
  '/municipios': typeof MunicipiosRoute
  '/receita': typeof ReceitaRoute
  '/sig': typeof SigRoute
  '/vigencias': typeof VigenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aero': typeof AeroRoute
  '/atas': typeof AtasRoute
  '/municipios': typeof MunicipiosRoute
  '/receita': typeof ReceitaRoute
  '/sig': typeof SigRoute
  '/vigencias': typeof VigenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aero': typeof AeroRoute
  '/atas': typeof AtasRoute
  '/municipios': typeof MunicipiosRoute
  '/receita': typeof ReceitaRoute
  '/sig': typeof SigRoute
  '/vigencias': typeof VigenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aero'
    | '/atas'
    | '/municipios'
    | '/receita'
    | '/sig'
    | '/vigencias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aero'
    | '/atas'
    | '/municipios'
    | '/receita'
    | '/sig'
    | '/vigencias'
  id:
    | '__root__'
    | '/'
    | '/aero'
    | '/atas'
    | '/municipios'
    | '/receita'
    | '/sig'
    | '/vigencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AeroRoute: typeof AeroRoute
  AtasRoute: typeof AtasRoute
  MunicipiosRoute: typeof MunicipiosRoute
  ReceitaRoute: typeof ReceitaRoute
  SigRoute: typeof SigRoute
  VigenciasRoute: typeof VigenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vigencias': {
      id: '/vigencias'
      path: '/vigencias'
      fullPath: '/vigencias'
      preLoaderRoute: typeof VigenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sig': {
      id: '/sig'
      path: '/sig'
      fullPath: '/sig'
      preLoaderRoute: typeof SigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita': {
      id: '/receita'
      path: '/receita'
      fullPath: '/receita'
      preLoaderRoute: typeof ReceitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipios': {
      id: '/municipios'
      path: '/municipios'
      fullPath: '/municipios'
      preLoaderRoute: typeof MunicipiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atas': {
      id: '/atas'
      path: '/atas'
      fullPath: '/atas'
      preLoaderRoute: typeof AtasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aero': {
      id: '/aero'
      path: '/aero'
      fullPath: '/aero'
      preLoaderRoute: typeof AeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AeroRoute: AeroRoute,
  AtasRoute: AtasRoute,
  MunicipiosRoute: MunicipiosRoute,
  ReceitaRoute: ReceitaRoute,
  SigRoute: SigRoute,
  VigenciasRoute: VigenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
